channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - networkx
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - pandas
  - jupyterlab
  - wandb