channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - networkx
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - pandas
  - jupyterlab
  - wandb
  - scikit-learn
  - tqdm
  - rdkit
  - pip:
      - torch-cluster==1.6.3
      - torch-geometric==2.4.0
      - torch-scatter==2.1.2
      - torch-sparse==0.6.18
      - torch-spline-conv==1.2.2