channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - networkx
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - pandas
  - jupyterlab
  - wandb
  - pip:
      - joblib==1.3.2
      - pyg-lib==0.3.1+pt21
      - scikit-learn==1.3.2
      - threadpoolctl==3.2.0
      - torch-cluster==1.6.3
      - torch-geometric==2.4.0
      - torch-scatter==2.1.2
      - torch-sparse==0.6.18
      - torch-spline-conv==1.2.2
      - tqdm==4.66.1