channels:
  - pyg
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.0.1=py3.10_cuda11.8_cudnn8.7.0_0
  - pytorch-cuda=11.8
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - pyg=2.3.1
  - networkx=3.1
  - numpy=1.26
  - scipy=1.11.1
  - matplotlib=3.7.2
  - seaborn
  - pandas=2.0.3
  - jupyterlab=3.6.3
  - wandb=0.15.11
  - rdkit=2023.09.4
  - black=24.1.1
  - pot=0.9.3
  - pytest=8.0.0
  - pytest-cov=4.1.0
  - einops=0.7.0
  - loguru=0.7.2
  - geomloss=0.2.6
  - pip
  - pip:
      - geomloss==0.2.6
