name: multi_test

on:
  push:
  pull_request:

jobs:
  run_tests:
    name: Test on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix: 
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }} 

    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH

    - name: Prepare environment file (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sed '/  - python=3.11/d' environment_docker.yml > environment_ubuntu.yml

    - name: Prepare environment file (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        sed '/  - python=3.11/d' environment.yml > environment_macos.yml

    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: conda env update --file environment_ubuntu.yml --name base

    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: conda env update --file environment_macos.yml --name base

    - name: Run tests
      run: python -m pytest --capture=no --cov=graphdiffusion --cov-report=term --cov-report=xml:coverage.xml
