name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file environment_docker.yml --name base
    - name: Test with pytest
      run: |
        # conda install pytest
        python -m pytest --capture=no 
        # pytest

    - name: Test with pytest and check code coverage
      run: |
        # Run tests with coverage
        python -m pytest --capture=no --cov=graphdiffusion --cov-report=term --cov-report=xml:coverage.xml

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  
